version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    container_name: nest-postgres
    networks:
      - postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - /data/postgres:/data/postgres

  nestjs-api:
    image: nestjs-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres
    
  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env

networks:
  postgres:
    driver: bridge
